version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  api:
    image: 'registry.jmir.org/node:latest'
    volumes:
      - './api:/home/app'
    ports:
      - '0.0.0.0:1337:1337'
    command: 'nodemon .'
  ui:
    stdin_open: true
    image: 'registry.jmir.org/node:latest'
    volumes:
      - './ui:/home/app'
    ports:
      - '0.0.0.0:3000:3000'
    command: 'npm run dev'
  load-balancer:
    image: 'nginx:latest'
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/ssl:/etc/ssl'
    ports:
      - '0.0.0.0:80:80'
